version: '3.8'

services:
  postgres:
    image: docker.io/postgres:latest
    container_name: splitbill-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: splitbill
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: 