version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: splitbill-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: splitbill
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: